/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class dtLink {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtLink(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtLink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtLink(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef(long value) {
    RecastJNI.dtLink_ref_set(swigCPtr, this, value);
  }

  public long getRef() {
    return RecastJNI.dtLink_ref_get(swigCPtr, this);
  }

  public void setNext(long value) {
    RecastJNI.dtLink_next_set(swigCPtr, this, value);
  }

  public long getNext() {
    return RecastJNI.dtLink_next_get(swigCPtr, this);
  }

  public void setEdge(short value) {
    RecastJNI.dtLink_edge_set(swigCPtr, this, value);
  }

  public short getEdge() {
    return RecastJNI.dtLink_edge_get(swigCPtr, this);
  }

  public void setSide(short value) {
    RecastJNI.dtLink_side_set(swigCPtr, this, value);
  }

  public short getSide() {
    return RecastJNI.dtLink_side_get(swigCPtr, this);
  }

  public void setBmin(short value) {
    RecastJNI.dtLink_bmin_set(swigCPtr, this, value);
  }

  public short getBmin() {
    return RecastJNI.dtLink_bmin_get(swigCPtr, this);
  }

  public void setBmax(short value) {
    RecastJNI.dtLink_bmax_set(swigCPtr, this, value);
  }

  public short getBmax() {
    return RecastJNI.dtLink_bmax_get(swigCPtr, this);
  }

  public dtLink() {
    this(RecastJNI.new_dtLink(), true);
  }

}
