/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class dtMeshHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtMeshHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtMeshHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtMeshHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMagic(int value) {
    RecastJNI.dtMeshHeader_magic_set(swigCPtr, this, value);
  }

  public int getMagic() {
    return RecastJNI.dtMeshHeader_magic_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    RecastJNI.dtMeshHeader_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return RecastJNI.dtMeshHeader_version_get(swigCPtr, this);
  }

  public void setX(int value) {
    RecastJNI.dtMeshHeader_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return RecastJNI.dtMeshHeader_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    RecastJNI.dtMeshHeader_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return RecastJNI.dtMeshHeader_y_get(swigCPtr, this);
  }

  public void setLayer(int value) {
    RecastJNI.dtMeshHeader_layer_set(swigCPtr, this, value);
  }

  public int getLayer() {
    return RecastJNI.dtMeshHeader_layer_get(swigCPtr, this);
  }

  public void setUserId(long value) {
    RecastJNI.dtMeshHeader_userId_set(swigCPtr, this, value);
  }

  public long getUserId() {
    return RecastJNI.dtMeshHeader_userId_get(swigCPtr, this);
  }

  public void setPolyCount(int value) {
    RecastJNI.dtMeshHeader_polyCount_set(swigCPtr, this, value);
  }

  public int getPolyCount() {
    return RecastJNI.dtMeshHeader_polyCount_get(swigCPtr, this);
  }

  public void setVertCount(int value) {
    RecastJNI.dtMeshHeader_vertCount_set(swigCPtr, this, value);
  }

  public int getVertCount() {
    return RecastJNI.dtMeshHeader_vertCount_get(swigCPtr, this);
  }

  public void setMaxLinkCount(int value) {
    RecastJNI.dtMeshHeader_maxLinkCount_set(swigCPtr, this, value);
  }

  public int getMaxLinkCount() {
    return RecastJNI.dtMeshHeader_maxLinkCount_get(swigCPtr, this);
  }

  public void setDetailMeshCount(int value) {
    RecastJNI.dtMeshHeader_detailMeshCount_set(swigCPtr, this, value);
  }

  public int getDetailMeshCount() {
    return RecastJNI.dtMeshHeader_detailMeshCount_get(swigCPtr, this);
  }

  public void setDetailVertCount(int value) {
    RecastJNI.dtMeshHeader_detailVertCount_set(swigCPtr, this, value);
  }

  public int getDetailVertCount() {
    return RecastJNI.dtMeshHeader_detailVertCount_get(swigCPtr, this);
  }

  public void setDetailTriCount(int value) {
    RecastJNI.dtMeshHeader_detailTriCount_set(swigCPtr, this, value);
  }

  public int getDetailTriCount() {
    return RecastJNI.dtMeshHeader_detailTriCount_get(swigCPtr, this);
  }

  public void setBvNodeCount(int value) {
    RecastJNI.dtMeshHeader_bvNodeCount_set(swigCPtr, this, value);
  }

  public int getBvNodeCount() {
    return RecastJNI.dtMeshHeader_bvNodeCount_get(swigCPtr, this);
  }

  public void setOffMeshConCount(int value) {
    RecastJNI.dtMeshHeader_offMeshConCount_set(swigCPtr, this, value);
  }

  public int getOffMeshConCount() {
    return RecastJNI.dtMeshHeader_offMeshConCount_get(swigCPtr, this);
  }

  public void setOffMeshBase(int value) {
    RecastJNI.dtMeshHeader_offMeshBase_set(swigCPtr, this, value);
  }

  public int getOffMeshBase() {
    return RecastJNI.dtMeshHeader_offMeshBase_get(swigCPtr, this);
  }

  public void setWalkableHeight(float value) {
    RecastJNI.dtMeshHeader_walkableHeight_set(swigCPtr, this, value);
  }

  public float getWalkableHeight() {
    return RecastJNI.dtMeshHeader_walkableHeight_get(swigCPtr, this);
  }

  public void setWalkableRadius(float value) {
    RecastJNI.dtMeshHeader_walkableRadius_set(swigCPtr, this, value);
  }

  public float getWalkableRadius() {
    return RecastJNI.dtMeshHeader_walkableRadius_get(swigCPtr, this);
  }

  public void setWalkableClimb(float value) {
    RecastJNI.dtMeshHeader_walkableClimb_set(swigCPtr, this, value);
  }

  public float getWalkableClimb() {
    return RecastJNI.dtMeshHeader_walkableClimb_get(swigCPtr, this);
  }

  public void setBmin(SWIGTYPE_p_float value) {
    RecastJNI.dtMeshHeader_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = RecastJNI.dtMeshHeader_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    RecastJNI.dtMeshHeader_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = RecastJNI.dtMeshHeader_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBvQuantFactor(float value) {
    RecastJNI.dtMeshHeader_bvQuantFactor_set(swigCPtr, this, value);
  }

  public float getBvQuantFactor() {
    return RecastJNI.dtMeshHeader_bvQuantFactor_get(swigCPtr, this);
  }

  public dtMeshHeader() {
    this(RecastJNI.new_dtMeshHeader(), true);
  }

}
