/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public final class dtNodeFlags {
  public final static dtNodeFlags DT_NODE_OPEN = new dtNodeFlags("DT_NODE_OPEN", RecastJNI.DT_NODE_OPEN_get());
  public final static dtNodeFlags DT_NODE_CLOSED = new dtNodeFlags("DT_NODE_CLOSED", RecastJNI.DT_NODE_CLOSED_get());
  public final static dtNodeFlags DT_NODE_PARENT_DETACHED = new dtNodeFlags("DT_NODE_PARENT_DETACHED", RecastJNI.DT_NODE_PARENT_DETACHED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtNodeFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtNodeFlags.class + " with value " + swigValue);
  }

  private dtNodeFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtNodeFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtNodeFlags(String swigName, dtNodeFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtNodeFlags[] swigValues = { DT_NODE_OPEN, DT_NODE_CLOSED, DT_NODE_PARENT_DETACHED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

