/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class dtNode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(SWIGTYPE_p_float value) {
    RecastJNI.dtNode_pos_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getPos() {
    long cPtr = RecastJNI.dtNode_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCost(float value) {
    RecastJNI.dtNode_cost_set(swigCPtr, this, value);
  }

  public float getCost() {
    return RecastJNI.dtNode_cost_get(swigCPtr, this);
  }

  public void setTotal(float value) {
    RecastJNI.dtNode_total_set(swigCPtr, this, value);
  }

  public float getTotal() {
    return RecastJNI.dtNode_total_get(swigCPtr, this);
  }

  public void setPidx(long value) {
    RecastJNI.dtNode_pidx_set(swigCPtr, this, value);
  }

  public long getPidx() {
    return RecastJNI.dtNode_pidx_get(swigCPtr, this);
  }

  public void setState(long value) {
    RecastJNI.dtNode_state_set(swigCPtr, this, value);
  }

  public long getState() {
    return RecastJNI.dtNode_state_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    RecastJNI.dtNode_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return RecastJNI.dtNode_flags_get(swigCPtr, this);
  }

  public void setId(long value) {
    RecastJNI.dtNode_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return RecastJNI.dtNode_id_get(swigCPtr, this);
  }

  public dtNode() {
    this(RecastJNI.new_dtNode(), true);
  }

}
