/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class dtPolyDetail {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtPolyDetail(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtPolyDetail obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtPolyDetail(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVertBase(long value) {
    RecastJNI.dtPolyDetail_vertBase_set(swigCPtr, this, value);
  }

  public long getVertBase() {
    return RecastJNI.dtPolyDetail_vertBase_get(swigCPtr, this);
  }

  public void setTriBase(long value) {
    RecastJNI.dtPolyDetail_triBase_set(swigCPtr, this, value);
  }

  public long getTriBase() {
    return RecastJNI.dtPolyDetail_triBase_get(swigCPtr, this);
  }

  public void setVertCount(short value) {
    RecastJNI.dtPolyDetail_vertCount_set(swigCPtr, this, value);
  }

  public short getVertCount() {
    return RecastJNI.dtPolyDetail_vertCount_get(swigCPtr, this);
  }

  public void setTriCount(short value) {
    RecastJNI.dtPolyDetail_triCount_set(swigCPtr, this, value);
  }

  public short getTriCount() {
    return RecastJNI.dtPolyDetail_triCount_get(swigCPtr, this);
  }

  public dtPolyDetail() {
    this(RecastJNI.new_dtPolyDetail(), true);
  }

}
