/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class dtQueryFilter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtQueryFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtQueryFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtQueryFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public dtQueryFilter() {
    this(RecastJNI.new_dtQueryFilter(), true);
  }

  public boolean passFilter(long ref, dtMeshTile tile, dtPoly poly) {
    return RecastJNI.dtQueryFilter_passFilter(swigCPtr, this, ref, dtMeshTile.getCPtr(tile), tile, dtPoly.getCPtr(poly), poly);
  }

  public float getCost(SWIGTYPE_p_float pa, SWIGTYPE_p_float pb, long prevRef, dtMeshTile prevTile, dtPoly prevPoly, long curRef, dtMeshTile curTile, dtPoly curPoly, long nextRef, dtMeshTile nextTile, dtPoly nextPoly) {
    return RecastJNI.dtQueryFilter_getCost(swigCPtr, this, SWIGTYPE_p_float.getCPtr(pa), SWIGTYPE_p_float.getCPtr(pb), prevRef, dtMeshTile.getCPtr(prevTile), prevTile, dtPoly.getCPtr(prevPoly), prevPoly, curRef, dtMeshTile.getCPtr(curTile), curTile, dtPoly.getCPtr(curPoly), curPoly, nextRef, dtMeshTile.getCPtr(nextTile), nextTile, dtPoly.getCPtr(nextPoly), nextPoly);
  }

  public float getAreaCost(int i) {
    return RecastJNI.dtQueryFilter_getAreaCost(swigCPtr, this, i);
  }

  public void setAreaCost(int i, float cost) {
    RecastJNI.dtQueryFilter_setAreaCost(swigCPtr, this, i, cost);
  }

  public int getIncludeFlags() {
    return RecastJNI.dtQueryFilter_getIncludeFlags(swigCPtr, this);
  }

  public void setIncludeFlags(int flags) {
    RecastJNI.dtQueryFilter_setIncludeFlags(swigCPtr, this, flags);
  }

  public int getExcludeFlags() {
    return RecastJNI.dtQueryFilter_getExcludeFlags(swigCPtr, this);
  }

  public void setExcludeFlags(int flags) {
    RecastJNI.dtQueryFilter_setExcludeFlags(swigCPtr, this, flags);
  }

}
