/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class rcContext {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rcContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rcContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public rcContext(boolean state) {
    this(RecastJNI.new_rcContext__SWIG_0(state), true);
  }

  public rcContext() {
    this(RecastJNI.new_rcContext__SWIG_1(), true);
  }

  public void enableLog(boolean state) {
    RecastJNI.rcContext_enableLog(swigCPtr, this, state);
  }

  public void resetLog() {
    RecastJNI.rcContext_resetLog(swigCPtr, this);
  }

  public void log(rcLogCategory category, String format) {
    RecastJNI.rcContext_log(swigCPtr, this, category.swigValue(), format);
  }

  public void enableTimer(boolean state) {
    RecastJNI.rcContext_enableTimer(swigCPtr, this, state);
  }

  public void resetTimers() {
    RecastJNI.rcContext_resetTimers(swigCPtr, this);
  }

  public void startTimer(rcTimerLabel label) {
    RecastJNI.rcContext_startTimer(swigCPtr, this, label.swigValue());
  }

  public void stopTimer(rcTimerLabel label) {
    RecastJNI.rcContext_stopTimer(swigCPtr, this, label.swigValue());
  }

  public int getAccumulatedTime(rcTimerLabel label) {
    return RecastJNI.rcContext_getAccumulatedTime(swigCPtr, this, label.swigValue());
  }

}
