/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class rcCompactCell {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rcCompactCell(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rcCompactCell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcCompactCell(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(long value) {
    RecastJNI.rcCompactCell_index_set(swigCPtr, this, value);
  }

  public long getIndex() {
    return RecastJNI.rcCompactCell_index_get(swigCPtr, this);
  }

  public void setCount(long value) {
    RecastJNI.rcCompactCell_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return RecastJNI.rcCompactCell_count_get(swigCPtr, this);
  }

  public rcCompactCell() {
    this(RecastJNI.new_rcCompactCell(), true);
  }

}
