/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class rcHeightfield {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rcHeightfield(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rcHeightfield obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcHeightfield(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(int value) {
    RecastJNI.rcHeightfield_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return RecastJNI.rcHeightfield_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    RecastJNI.rcHeightfield_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return RecastJNI.rcHeightfield_height_get(swigCPtr, this);
  }

  public void setBmin(SWIGTYPE_p_float value) {
    RecastJNI.rcHeightfield_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = RecastJNI.rcHeightfield_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    RecastJNI.rcHeightfield_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = RecastJNI.rcHeightfield_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCs(float value) {
    RecastJNI.rcHeightfield_cs_set(swigCPtr, this, value);
  }

  public float getCs() {
    return RecastJNI.rcHeightfield_cs_get(swigCPtr, this);
  }

  public void setCh(float value) {
    RecastJNI.rcHeightfield_ch_set(swigCPtr, this, value);
  }

  public float getCh() {
    return RecastJNI.rcHeightfield_ch_get(swigCPtr, this);
  }

  public void setSpans(SWIGTYPE_p_p_rcSpan value) {
    RecastJNI.rcHeightfield_spans_set(swigCPtr, this, SWIGTYPE_p_p_rcSpan.getCPtr(value));
  }

  public SWIGTYPE_p_p_rcSpan getSpans() {
    long cPtr = RecastJNI.rcHeightfield_spans_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_rcSpan(cPtr, false);
  }

  public void setPools(rcSpanPool value) {
    RecastJNI.rcHeightfield_pools_set(swigCPtr, this, rcSpanPool.getCPtr(value), value);
  }

  public rcSpanPool getPools() {
    long cPtr = RecastJNI.rcHeightfield_pools_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rcSpanPool(cPtr, false);
  }

  public void setFreelist(rcSpan value) {
    RecastJNI.rcHeightfield_freelist_set(swigCPtr, this, rcSpan.getCPtr(value), value);
  }

  public rcSpan getFreelist() {
    long cPtr = RecastJNI.rcHeightfield_freelist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rcSpan(cPtr, false);
  }

  public rcHeightfield() {
    this(RecastJNI.new_rcHeightfield(), true);
  }

}
