/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class rcHeightfieldLayerSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rcHeightfieldLayerSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rcHeightfieldLayerSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcHeightfieldLayerSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLayers(rcHeightfieldLayer value) {
    RecastJNI.rcHeightfieldLayerSet_layers_set(swigCPtr, this, rcHeightfieldLayer.getCPtr(value), value);
  }

  public rcHeightfieldLayer getLayers() {
    long cPtr = RecastJNI.rcHeightfieldLayerSet_layers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rcHeightfieldLayer(cPtr, false);
  }

  public void setNlayers(int value) {
    RecastJNI.rcHeightfieldLayerSet_nlayers_set(swigCPtr, this, value);
  }

  public int getNlayers() {
    return RecastJNI.rcHeightfieldLayerSet_nlayers_get(swigCPtr, this);
  }

  public rcHeightfieldLayerSet() {
    this(RecastJNI.new_rcHeightfieldLayerSet(), true);
  }

}
