/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public class rcSpanPool {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rcSpanPool(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rcSpanPool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcSpanPool(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(rcSpanPool value) {
    RecastJNI.rcSpanPool_next_set(swigCPtr, this, rcSpanPool.getCPtr(value), value);
  }

  public rcSpanPool getNext() {
    long cPtr = RecastJNI.rcSpanPool_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rcSpanPool(cPtr, false);
  }

  public void setItems(rcSpan value) {
    RecastJNI.rcSpanPool_items_set(swigCPtr, this, rcSpan.getCPtr(value), value);
  }

  public rcSpan getItems() {
    long cPtr = RecastJNI.rcSpanPool_items_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rcSpan(cPtr, false);
  }

  public rcSpanPool() {
    this(RecastJNI.new_rcSpanPool(), true);
  }

}
