/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.recast;

public final class rcTimerLabel {
  public final static rcTimerLabel RC_TIMER_TOTAL = new rcTimerLabel("RC_TIMER_TOTAL");
  public final static rcTimerLabel RC_TIMER_TEMP = new rcTimerLabel("RC_TIMER_TEMP");
  public final static rcTimerLabel RC_TIMER_RASTERIZE_TRIANGLES = new rcTimerLabel("RC_TIMER_RASTERIZE_TRIANGLES");
  public final static rcTimerLabel RC_TIMER_BUILD_COMPACTHEIGHTFIELD = new rcTimerLabel("RC_TIMER_BUILD_COMPACTHEIGHTFIELD");
  public final static rcTimerLabel RC_TIMER_BUILD_CONTOURS = new rcTimerLabel("RC_TIMER_BUILD_CONTOURS");
  public final static rcTimerLabel RC_TIMER_BUILD_CONTOURS_TRACE = new rcTimerLabel("RC_TIMER_BUILD_CONTOURS_TRACE");
  public final static rcTimerLabel RC_TIMER_BUILD_CONTOURS_SIMPLIFY = new rcTimerLabel("RC_TIMER_BUILD_CONTOURS_SIMPLIFY");
  public final static rcTimerLabel RC_TIMER_FILTER_BORDER = new rcTimerLabel("RC_TIMER_FILTER_BORDER");
  public final static rcTimerLabel RC_TIMER_FILTER_WALKABLE = new rcTimerLabel("RC_TIMER_FILTER_WALKABLE");
  public final static rcTimerLabel RC_TIMER_MEDIAN_AREA = new rcTimerLabel("RC_TIMER_MEDIAN_AREA");
  public final static rcTimerLabel RC_TIMER_FILTER_LOW_OBSTACLES = new rcTimerLabel("RC_TIMER_FILTER_LOW_OBSTACLES");
  public final static rcTimerLabel RC_TIMER_BUILD_POLYMESH = new rcTimerLabel("RC_TIMER_BUILD_POLYMESH");
  public final static rcTimerLabel RC_TIMER_MERGE_POLYMESH = new rcTimerLabel("RC_TIMER_MERGE_POLYMESH");
  public final static rcTimerLabel RC_TIMER_ERODE_AREA = new rcTimerLabel("RC_TIMER_ERODE_AREA");
  public final static rcTimerLabel RC_TIMER_MARK_BOX_AREA = new rcTimerLabel("RC_TIMER_MARK_BOX_AREA");
  public final static rcTimerLabel RC_TIMER_MARK_CYLINDER_AREA = new rcTimerLabel("RC_TIMER_MARK_CYLINDER_AREA");
  public final static rcTimerLabel RC_TIMER_MARK_CONVEXPOLY_AREA = new rcTimerLabel("RC_TIMER_MARK_CONVEXPOLY_AREA");
  public final static rcTimerLabel RC_TIMER_BUILD_DISTANCEFIELD = new rcTimerLabel("RC_TIMER_BUILD_DISTANCEFIELD");
  public final static rcTimerLabel RC_TIMER_BUILD_DISTANCEFIELD_DIST = new rcTimerLabel("RC_TIMER_BUILD_DISTANCEFIELD_DIST");
  public final static rcTimerLabel RC_TIMER_BUILD_DISTANCEFIELD_BLUR = new rcTimerLabel("RC_TIMER_BUILD_DISTANCEFIELD_BLUR");
  public final static rcTimerLabel RC_TIMER_BUILD_REGIONS = new rcTimerLabel("RC_TIMER_BUILD_REGIONS");
  public final static rcTimerLabel RC_TIMER_BUILD_REGIONS_WATERSHED = new rcTimerLabel("RC_TIMER_BUILD_REGIONS_WATERSHED");
  public final static rcTimerLabel RC_TIMER_BUILD_REGIONS_EXPAND = new rcTimerLabel("RC_TIMER_BUILD_REGIONS_EXPAND");
  public final static rcTimerLabel RC_TIMER_BUILD_REGIONS_FLOOD = new rcTimerLabel("RC_TIMER_BUILD_REGIONS_FLOOD");
  public final static rcTimerLabel RC_TIMER_BUILD_REGIONS_FILTER = new rcTimerLabel("RC_TIMER_BUILD_REGIONS_FILTER");
  public final static rcTimerLabel RC_TIMER_BUILD_LAYERS = new rcTimerLabel("RC_TIMER_BUILD_LAYERS");
  public final static rcTimerLabel RC_TIMER_BUILD_POLYMESHDETAIL = new rcTimerLabel("RC_TIMER_BUILD_POLYMESHDETAIL");
  public final static rcTimerLabel RC_TIMER_MERGE_POLYMESHDETAIL = new rcTimerLabel("RC_TIMER_MERGE_POLYMESHDETAIL");
  public final static rcTimerLabel RC_MAX_TIMERS = new rcTimerLabel("RC_MAX_TIMERS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static rcTimerLabel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + rcTimerLabel.class + " with value " + swigValue);
  }

  private rcTimerLabel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private rcTimerLabel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private rcTimerLabel(String swigName, rcTimerLabel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static rcTimerLabel[] swigValues = { RC_TIMER_TOTAL, RC_TIMER_TEMP, RC_TIMER_RASTERIZE_TRIANGLES, RC_TIMER_BUILD_COMPACTHEIGHTFIELD, RC_TIMER_BUILD_CONTOURS, RC_TIMER_BUILD_CONTOURS_TRACE, RC_TIMER_BUILD_CONTOURS_SIMPLIFY, RC_TIMER_FILTER_BORDER, RC_TIMER_FILTER_WALKABLE, RC_TIMER_MEDIAN_AREA, RC_TIMER_FILTER_LOW_OBSTACLES, RC_TIMER_BUILD_POLYMESH, RC_TIMER_MERGE_POLYMESH, RC_TIMER_ERODE_AREA, RC_TIMER_MARK_BOX_AREA, RC_TIMER_MARK_CYLINDER_AREA, RC_TIMER_MARK_CONVEXPOLY_AREA, RC_TIMER_BUILD_DISTANCEFIELD, RC_TIMER_BUILD_DISTANCEFIELD_DIST, RC_TIMER_BUILD_DISTANCEFIELD_BLUR, RC_TIMER_BUILD_REGIONS, RC_TIMER_BUILD_REGIONS_WATERSHED, RC_TIMER_BUILD_REGIONS_EXPAND, RC_TIMER_BUILD_REGIONS_FLOOD, RC_TIMER_BUILD_REGIONS_FILTER, RC_TIMER_BUILD_LAYERS, RC_TIMER_BUILD_POLYMESHDETAIL, RC_TIMER_MERGE_POLYMESHDETAIL, RC_MAX_TIMERS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

