/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.Detour;

public class dtNavMeshParams {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtNavMeshParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtNavMeshParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DetourJNI.delete_dtNavMeshParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrig(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshParams_orig_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getOrig() {
    long cPtr = DetourJNI.dtNavMeshParams_orig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTileWidth(float value) {
    DetourJNI.dtNavMeshParams_tileWidth_set(swigCPtr, this, value);
  }

  public float getTileWidth() {
    return DetourJNI.dtNavMeshParams_tileWidth_get(swigCPtr, this);
  }

  public void setTileHeight(float value) {
    DetourJNI.dtNavMeshParams_tileHeight_set(swigCPtr, this, value);
  }

  public float getTileHeight() {
    return DetourJNI.dtNavMeshParams_tileHeight_get(swigCPtr, this);
  }

  public void setMaxTiles(int value) {
    DetourJNI.dtNavMeshParams_maxTiles_set(swigCPtr, this, value);
  }

  public int getMaxTiles() {
    return DetourJNI.dtNavMeshParams_maxTiles_get(swigCPtr, this);
  }

  public void setMaxPolys(int value) {
    DetourJNI.dtNavMeshParams_maxPolys_set(swigCPtr, this, value);
  }

  public int getMaxPolys() {
    return DetourJNI.dtNavMeshParams_maxPolys_get(swigCPtr, this);
  }

  public dtNavMeshParams() {
    this(DetourJNI.new_dtNavMeshParams(), true);
  }

}
