/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.detour;

public class dtNavMeshCreateParams {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtNavMeshCreateParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtNavMeshCreateParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DetourJNI.delete_dtNavMeshCreateParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVerts(SWIGTYPE_p_unsigned_short value) {
    DetourJNI.dtNavMeshCreateParams_verts_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getVerts() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_verts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setVertCount(int value) {
    DetourJNI.dtNavMeshCreateParams_vertCount_set(swigCPtr, this, value);
  }

  public int getVertCount() {
    return DetourJNI.dtNavMeshCreateParams_vertCount_get(swigCPtr, this);
  }

  public void setPolys(SWIGTYPE_p_unsigned_short value) {
    DetourJNI.dtNavMeshCreateParams_polys_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getPolys() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_polys_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setPolyFlags(SWIGTYPE_p_unsigned_short value) {
    DetourJNI.dtNavMeshCreateParams_polyFlags_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getPolyFlags() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_polyFlags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setPolyAreas(SWIGTYPE_p_unsigned_char value) {
    DetourJNI.dtNavMeshCreateParams_polyAreas_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPolyAreas() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_polyAreas_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPolyCount(int value) {
    DetourJNI.dtNavMeshCreateParams_polyCount_set(swigCPtr, this, value);
  }

  public int getPolyCount() {
    return DetourJNI.dtNavMeshCreateParams_polyCount_get(swigCPtr, this);
  }

  public void setNvp(int value) {
    DetourJNI.dtNavMeshCreateParams_nvp_set(swigCPtr, this, value);
  }

  public int getNvp() {
    return DetourJNI.dtNavMeshCreateParams_nvp_get(swigCPtr, this);
  }

  public void setDetailMeshes(SWIGTYPE_p_unsigned_int value) {
    DetourJNI.dtNavMeshCreateParams_detailMeshes_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDetailMeshes() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_detailMeshes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setDetailVerts(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshCreateParams_detailVerts_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getDetailVerts() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_detailVerts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setDetailVertsCount(int value) {
    DetourJNI.dtNavMeshCreateParams_detailVertsCount_set(swigCPtr, this, value);
  }

  public int getDetailVertsCount() {
    return DetourJNI.dtNavMeshCreateParams_detailVertsCount_get(swigCPtr, this);
  }

  public void setDetailTris(SWIGTYPE_p_unsigned_char value) {
    DetourJNI.dtNavMeshCreateParams_detailTris_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDetailTris() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_detailTris_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDetailTriCount(int value) {
    DetourJNI.dtNavMeshCreateParams_detailTriCount_set(swigCPtr, this, value);
  }

  public int getDetailTriCount() {
    return DetourJNI.dtNavMeshCreateParams_detailTriCount_get(swigCPtr, this);
  }

  public void setOffMeshConVerts(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConVerts_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getOffMeshConVerts() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConVerts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setOffMeshConRad(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConRad_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getOffMeshConRad() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConRad_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setOffMeshConFlags(SWIGTYPE_p_unsigned_short value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConFlags_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getOffMeshConFlags() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConFlags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setOffMeshConAreas(SWIGTYPE_p_unsigned_char value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConAreas_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getOffMeshConAreas() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConAreas_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setOffMeshConDir(SWIGTYPE_p_unsigned_char value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConDir_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getOffMeshConDir() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConDir_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setOffMeshConUserID(SWIGTYPE_p_unsigned_int value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConUserID_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getOffMeshConUserID() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_offMeshConUserID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setOffMeshConCount(int value) {
    DetourJNI.dtNavMeshCreateParams_offMeshConCount_set(swigCPtr, this, value);
  }

  public int getOffMeshConCount() {
    return DetourJNI.dtNavMeshCreateParams_offMeshConCount_get(swigCPtr, this);
  }

  public void setUserId(long value) {
    DetourJNI.dtNavMeshCreateParams_userId_set(swigCPtr, this, value);
  }

  public long getUserId() {
    return DetourJNI.dtNavMeshCreateParams_userId_get(swigCPtr, this);
  }

  public void setTileX(int value) {
    DetourJNI.dtNavMeshCreateParams_tileX_set(swigCPtr, this, value);
  }

  public int getTileX() {
    return DetourJNI.dtNavMeshCreateParams_tileX_get(swigCPtr, this);
  }

  public void setTileY(int value) {
    DetourJNI.dtNavMeshCreateParams_tileY_set(swigCPtr, this, value);
  }

  public int getTileY() {
    return DetourJNI.dtNavMeshCreateParams_tileY_get(swigCPtr, this);
  }

  public void setTileLayer(int value) {
    DetourJNI.dtNavMeshCreateParams_tileLayer_set(swigCPtr, this, value);
  }

  public int getTileLayer() {
    return DetourJNI.dtNavMeshCreateParams_tileLayer_get(swigCPtr, this);
  }

  public void setBmin(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshCreateParams_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    DetourJNI.dtNavMeshCreateParams_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = DetourJNI.dtNavMeshCreateParams_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setWalkableHeight(float value) {
    DetourJNI.dtNavMeshCreateParams_walkableHeight_set(swigCPtr, this, value);
  }

  public float getWalkableHeight() {
    return DetourJNI.dtNavMeshCreateParams_walkableHeight_get(swigCPtr, this);
  }

  public void setWalkableRadius(float value) {
    DetourJNI.dtNavMeshCreateParams_walkableRadius_set(swigCPtr, this, value);
  }

  public float getWalkableRadius() {
    return DetourJNI.dtNavMeshCreateParams_walkableRadius_get(swigCPtr, this);
  }

  public void setWalkableClimb(float value) {
    DetourJNI.dtNavMeshCreateParams_walkableClimb_set(swigCPtr, this, value);
  }

  public float getWalkableClimb() {
    return DetourJNI.dtNavMeshCreateParams_walkableClimb_get(swigCPtr, this);
  }

  public void setCs(float value) {
    DetourJNI.dtNavMeshCreateParams_cs_set(swigCPtr, this, value);
  }

  public float getCs() {
    return DetourJNI.dtNavMeshCreateParams_cs_get(swigCPtr, this);
  }

  public void setCh(float value) {
    DetourJNI.dtNavMeshCreateParams_ch_set(swigCPtr, this, value);
  }

  public float getCh() {
    return DetourJNI.dtNavMeshCreateParams_ch_get(swigCPtr, this);
  }

  public void setBuildBvTree(boolean value) {
    DetourJNI.dtNavMeshCreateParams_buildBvTree_set(swigCPtr, this, value);
  }

  public boolean getBuildBvTree() {
    return DetourJNI.dtNavMeshCreateParams_buildBvTree_get(swigCPtr, this);
  }

  public dtNavMeshCreateParams() {
    this(DetourJNI.new_dtNavMeshCreateParams(), true);
  }

}
