/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.Detour;

public final class dtPolyTypes {
  public final static dtPolyTypes DT_POLYTYPE_GROUND = new dtPolyTypes("DT_POLYTYPE_GROUND", DetourJNI.DT_POLYTYPE_GROUND_get());
  public final static dtPolyTypes DT_POLYTYPE_OFFMESH_CONNECTION = new dtPolyTypes("DT_POLYTYPE_OFFMESH_CONNECTION", DetourJNI.DT_POLYTYPE_OFFMESH_CONNECTION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtPolyTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtPolyTypes.class + " with value " + swigValue);
  }

  private dtPolyTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtPolyTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtPolyTypes(String swigName, dtPolyTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtPolyTypes[] swigValues = { DT_POLYTYPE_GROUND, DT_POLYTYPE_OFFMESH_CONNECTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

