/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.Detour;

public class dtRaycastHit {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dtRaycastHit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dtRaycastHit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DetourJNI.delete_dtRaycastHit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setT(float value) {
    DetourJNI.dtRaycastHit_t_set(swigCPtr, this, value);
  }

  public float getT() {
    return DetourJNI.dtRaycastHit_t_get(swigCPtr, this);
  }

  public void setHitNormal(SWIGTYPE_p_float value) {
    DetourJNI.dtRaycastHit_hitNormal_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getHitNormal() {
    long cPtr = DetourJNI.dtRaycastHit_hitNormal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setPath(SWIGTYPE_p_unsigned_int value) {
    DetourJNI.dtRaycastHit_path_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getPath() {
    long cPtr = DetourJNI.dtRaycastHit_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setPathCount(int value) {
    DetourJNI.dtRaycastHit_pathCount_set(swigCPtr, this, value);
  }

  public int getPathCount() {
    return DetourJNI.dtRaycastHit_pathCount_get(swigCPtr, this);
  }

  public void setMaxPath(int value) {
    DetourJNI.dtRaycastHit_maxPath_set(swigCPtr, this, value);
  }

  public int getMaxPath() {
    return DetourJNI.dtRaycastHit_maxPath_get(swigCPtr, this);
  }

  public void setPathCost(float value) {
    DetourJNI.dtRaycastHit_pathCost_set(swigCPtr, this, value);
  }

  public float getPathCost() {
    return DetourJNI.dtRaycastHit_pathCost_get(swigCPtr, this);
  }

  public dtRaycastHit() {
    this(DetourJNI.new_dtRaycastHit(), true);
  }

}
