/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.Detour;

public final class dtStraightPathFlags {
  public final static dtStraightPathFlags DT_STRAIGHTPATH_START = new dtStraightPathFlags("DT_STRAIGHTPATH_START", DetourJNI.DT_STRAIGHTPATH_START_get());
  public final static dtStraightPathFlags DT_STRAIGHTPATH_END = new dtStraightPathFlags("DT_STRAIGHTPATH_END", DetourJNI.DT_STRAIGHTPATH_END_get());
  public final static dtStraightPathFlags DT_STRAIGHTPATH_OFFMESH_CONNECTION = new dtStraightPathFlags("DT_STRAIGHTPATH_OFFMESH_CONNECTION", DetourJNI.DT_STRAIGHTPATH_OFFMESH_CONNECTION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtStraightPathFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtStraightPathFlags.class + " with value " + swigValue);
  }

  private dtStraightPathFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtStraightPathFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtStraightPathFlags(String swigName, dtStraightPathFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtStraightPathFlags[] swigValues = { DT_STRAIGHTPATH_START, DT_STRAIGHTPATH_END, DT_STRAIGHTPATH_OFFMESH_CONNECTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

