/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.detour;

public final class dtStraightPathOptions {
  public final static dtStraightPathOptions DT_STRAIGHTPATH_AREA_CROSSINGS = new dtStraightPathOptions("DT_STRAIGHTPATH_AREA_CROSSINGS", DetourJNI.DT_STRAIGHTPATH_AREA_CROSSINGS_get());
  public final static dtStraightPathOptions DT_STRAIGHTPATH_ALL_CROSSINGS = new dtStraightPathOptions("DT_STRAIGHTPATH_ALL_CROSSINGS", DetourJNI.DT_STRAIGHTPATH_ALL_CROSSINGS_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtStraightPathOptions swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtStraightPathOptions.class + " with value " + swigValue);
  }

  private dtStraightPathOptions(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtStraightPathOptions(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtStraightPathOptions(String swigName, dtStraightPathOptions swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtStraightPathOptions[] swigValues = { DT_STRAIGHTPATH_AREA_CROSSINGS, DT_STRAIGHTPATH_ALL_CROSSINGS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

