/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.laykun.Detour;

public final class dtTileFlags {
  public final static dtTileFlags DT_TILE_FREE_DATA = new dtTileFlags("DT_TILE_FREE_DATA", DetourJNI.DT_TILE_FREE_DATA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtTileFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtTileFlags.class + " with value " + swigValue);
  }

  private dtTileFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtTileFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtTileFlags(String swigName, dtTileFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtTileFlags[] swigValues = { DT_TILE_FREE_DATA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

